### ISSUE TITLE
delete 'Theme Scripts'

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/lua-reference-guide#3]
delete or mark as deprecated 'Theme Scripts' in Part I - Script Type Overview

**Comment by pfeerick** [comment]
It's been deleted for now, but may get re-instated at a later date as it could become the mechanism for preset themes... i.e. lua script that sets the colours. And the documentation for "Wizard Scripts" also leaves much to be desired... including the fact the entry even exists! 😆
